#
# This file is auto-generated. DO NOT EDIT
# Generated by: autospec.py
# Using build pattern: cmake
#
Name     : socket.io-client-cpp
Version  : 3.1.0
Release  : 1
URL      : https://github.com/socketio/socket.io-client-cpp/archive/3.1.0/socket.io-client-cpp-3.1.0.tar.gz
Source0  : https://github.com/socketio/socket.io-client-cpp/archive/3.1.0/socket.io-client-cpp-3.1.0.tar.gz
Summary  : No detailed summary available
Group    : Development/Tools
License  : MIT
Requires: socket.io-client-cpp-lib = %{version}-%{release}
Requires: socket.io-client-cpp-license = %{version}-%{release}
BuildRequires : asio-dev
BuildRequires : buildreq-cmake
BuildRequires : openssl-dev
BuildRequires : rapidjson-dev
BuildRequires : websocketpp-dev
# Suppress stripping binaries
%define __strip /bin/true
%define debug_package %{nil}

%description
# Socket.IO C++ Client
[![Build Status](https://github.com/socketio/socket.io-client-cpp/workflows/CI/badge.svg)](https://github.com/socketio/socket.io-client-cpp/actions)

%package dev
Summary: dev components for the socket.io-client-cpp package.
Group: Development
Requires: socket.io-client-cpp-lib = %{version}-%{release}
Provides: socket.io-client-cpp-devel = %{version}-%{release}
Requires: socket.io-client-cpp = %{version}-%{release}

%description dev
dev components for the socket.io-client-cpp package.


%package lib
Summary: lib components for the socket.io-client-cpp package.
Group: Libraries
Requires: socket.io-client-cpp-license = %{version}-%{release}

%description lib
lib components for the socket.io-client-cpp package.


%package license
Summary: license components for the socket.io-client-cpp package.
Group: Default

%description license
license components for the socket.io-client-cpp package.


%prep
%setup -q -n socket.io-client-cpp-3.1.0
cd %{_builddir}/socket.io-client-cpp-3.1.0

%build
export http_proxy=http://127.0.0.1:9/
export https_proxy=http://127.0.0.1:9/
export no_proxy=localhost,127.0.0.1,0.0.0.0
export LANG=C.UTF-8
export SOURCE_DATE_EPOCH=1685751029
mkdir -p clr-build
pushd clr-build
export GCC_IGNORE_WERROR=1
export AR=gcc-ar
export RANLIB=gcc-ranlib
export NM=gcc-nm
export CFLAGS="$CFLAGS -O3 -fdebug-types-section -femit-struct-debug-baseonly -ffat-lto-objects -flto=auto -g1 -gno-column-info -gno-variable-location-views -gz=zstd "
export FCFLAGS="$FFLAGS -O3 -fdebug-types-section -femit-struct-debug-baseonly -ffat-lto-objects -flto=auto -g1 -gno-column-info -gno-variable-location-views -gz=zstd "
export FFLAGS="$FFLAGS -O3 -fdebug-types-section -femit-struct-debug-baseonly -ffat-lto-objects -flto=auto -g1 -gno-column-info -gno-variable-location-views -gz=zstd "
export CXXFLAGS="$CXXFLAGS -O3 -fdebug-types-section -femit-struct-debug-baseonly -ffat-lto-objects -flto=auto -g1 -gno-column-info -gno-variable-location-views -gz=zstd "
%cmake .. -DCMAKE_BUILD_TYPE=Release
make  %{?_smp_mflags}
popd

%install
export SOURCE_DATE_EPOCH=1685751029
rm -rf %{buildroot}
mkdir -p %{buildroot}/usr/share/package-licenses/socket.io-client-cpp
cp %{_builddir}/socket.io-client-cpp-%{version}/LICENSE %{buildroot}/usr/share/package-licenses/socket.io-client-cpp/b3cb313c85da9e7d8160dacca03f253c97c7dcb8 || :
pushd clr-build
%make_install
popd

%files
%defattr(-,root,root,-)

%files dev
%defattr(-,root,root,-)
/usr/include/sio_client.h
/usr/include/sio_message.h
/usr/include/sio_socket.h
/usr/lib64/libsioclient.so
/usr/lib64/libsioclient_tls.so

%files lib
%defattr(-,root,root,-)
/usr/lib64/libsioclient.so.1
/usr/lib64/libsioclient.so.1.6.0
/usr/lib64/libsioclient_tls.so.1
/usr/lib64/libsioclient_tls.so.1.6.0

%files license
%defattr(0644,root,root,0755)
/usr/share/package-licenses/socket.io-client-cpp/b3cb313c85da9e7d8160dacca03f253c97c7dcb8
